apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: noobaa-db
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - noobaa-db
  resources:
  - securitycontextconstraints
  verbs:
  - use
