apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: noobaa-db
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
allowedCapabilities:
- SETUID
- SETGID
fsGroup:
  type: MustRunAs
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
