apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-validation-webhook
webhooks:
  - name: admissionwebhook.noobaa.io
    matchPolicy: Equivalent
    rules:
    - apiGroups:   ["noobaa.io"]
      apiVersions: ["v1alpha1"]
      operations:  
      - "CREATE" 
      - "UPDATE"
      - "DELETE"
      resources:   
      - "backingstores"
      - "namespacestores"
      scope: "Namespaced"
    - apiGroups:   ["noobaa.io"]
      apiVersions: ["v1alpha1"]
      operations:  
      - "CREATE" 
      resources:   
      - "bucketclasses"
      scope: "Namespaced"
    - apiGroups:   ["noobaa.io"]
      apiVersions: ["v1alpha1"]
      operations:  
      - "CREATE" 
      - "UPDATE"
      resources:   
      - "noobaaaccounts"
      scope: "Namespaced"
    - apiGroups:   ["noobaa.io"]
      apiVersions: ["v1alpha1"]
      operations:  
      - "DELETE"
      - "CREATE"
      - "UPDATE"
      resources:   
      - "noobaas"
      scope: "Namespaced"
    sideEffects: None
    clientConfig:
      service:
        name: admission-webhook-service
        namespace: placeholder
        path: "/validate"
      caBundle:
    admissionReviewVersions: ["v1", "v1beta1"]
    failurePolicy: Ignore
    timeoutSeconds: 5
