name: KMS Test - KMIP

# Run on each new PR and each new push to existing PR
on: [push, pull_request]

jobs:
  run-kms-kmip-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Set environment variables
        run: |
          echo PATH=$PATH:$HOME/go/bin                                          >> $GITHUB_ENV
          echo OPERATOR_IMAGE=localhost:5000/noobaa/noobaa-operator:integration >> $GITHUB_ENV
          echo PYKMIP_IMAGE=localhost:5000/noobaa/pykmip:integration >> $GITHUB_ENV
      
      - name: Deploy Dependencies
        run: |
          bash .travis/install-5nodes-kind-cluster.sh
          go get -v github.com/onsi/ginkgo/ginkgo
          ginkgo version
          
      - name: Build NooBaa
        run: |
          make cli
          make image
          docker tag noobaa/noobaa-operator:$(go run cmd/version/main.go) $OPERATOR_IMAGE
          docker push $OPERATOR_IMAGE

      - name: Install NooBaa, KMIP server and certs
        run: |
          bash -x .travis/install-kmip-kms-noobaa.sh

      - name: Run KMS KMIP test
        run: make test-kms-kmip
